config/routes.rb
Rails.application.routes.draw do
  root "gossips#index"
  get '/welcome', to: 'gossips#index'
  get '/welcome/:first_name', to: 'gossips#index'
  get '/team', to: 'static#team'
  get '/contact', to: 'static#contact'

  resources :gossips do
    resources :comments
  end

  resources :profils, only: [:index,:show]
  resources :cities, only: [:index,:show]
  



  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  # get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/city.rb
class City < ApplicationRecord
  has_many :users
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :gossip
  
end

app/models/gossip.rb
class Gossip < ApplicationRecord
  validates :title, 
    presence: true, 
    length: { in: 3..14 }
  validates :content, presence: true

  belongs_to :user
  has_many :comments
  has_many :join_tag_with_gossips
  has_many :tags, through: :join_tag_with_gossips
end

app/models/join_tag_with_gossip.rb
class JoinTagWithGossip < ApplicationRecord
  belongs_to :gossip
  belongs_to :tag
end

app/models/private_message.rb
class PrivateMessage < ApplicationRecord
  belongs_to :sender, class_name: "User"
  belongs_to :recipient, class_name: "User"
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :join_tag_with_gossips
  has_many :gossips, through: :join_tag_with_gossips
end

app/models/user.rb
class User < ApplicationRecord
  belongs_to :city
  has_many :gossips
  has_many :comments
  has_many :sent_messages, foreign_key: 'sender_id', class_name: "PrivateMessage"
  has_many :received_messages, foreign_key: 'recipient_id', class_name: "PrivateMessage"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception # Prevent CSRF attacks by raising an exception.
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
  def index
    @cities = City.all
  end

  def show
    puts "%"*60
    puts @id
    puts "%"*60
    @city = City.find(params[:id])
    

  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def index
    puts "%"*50
    puts "Dans index comment :"
    puts params
    puts "%"*50 
    @comments = Comment.all
    @gossip = Gossip.find(params[:gossip_id])
  end

  def new    
    @comment = Comment.new
    puts "%"*50
    puts "Dans new comment :"
    puts params
    puts "%"*50    
  end

  def create
    puts "%"*50
    puts "Lorsque je soumet la création du commentaire :"
    puts params    
    puts "%"*50
    @gossip = Gossip.find(params[:gossip_id])
    @comment = Comment.new(content:params[:content],user:@gossip.user,gossip:@gossip)
    if @comment.save
      redirect_to @gossip
    else
      render "gossip/show", status: :unprocessable_entity
    end
  end

  def edit
    puts "%"*50
    puts "Lorsque je suis dans l'edit du commentaire :"
    puts params    
    puts "%"*50
    @comment = Comment.find(params[:id])
    @gossip = Gossip.find(params[:gossip_id])
  end

  def update    
    puts "%"*50
    puts "Lorsque je soumet la modofication du commentaire :"
    puts params 
    comment_params = params.require(:comment).permit(:content)
    @comment = Comment.find(params[:id])
    @gossip = Gossip.find(params[:gossip_id])
    puts "%"*50
    if @comment.update(content:comment_params[:content],user:@gossip.user,gossip:@gossip)
      redirect_to @gossip
    else
      render "gossip/show", status: :unprocessable_entity
    end
  end

  def destroy
    puts "%"*50
    puts "Lorsque je soumet la suppression du commentaire :"
    puts params     
    puts "%"*50
    @gossip = Gossip.find(params[:gossip_id])
    @comment = Comment.find(params[:id])
    @comment.destroy
    puts "le commentaire id :#{params[:id]} a été supprimé"
    redirect_to @gossip
  end


  
end

app/controllers/gossips_controller.rb
class GossipsController < ApplicationController
    def index
      puts "$" * 60
      puts "Voici le param de la page welcome :"
      puts  params[:first_name]
      puts "$" * 60    
      @first_name = params[:first_name]
      @gossips = Gossip.all
      
    end

    def show
        puts "$" * 60
        puts "Voici le params de la page gossip show :"
        puts  params[:id]
        puts "$" * 60    
        @id = params[:id]
        @gossip = Gossip.find(@id)

        #Partie commentaire
        @comments = Comment.all
    end
    
    def edit
      @id = params[:id]
      @gossip = Gossip.find(@id)
    end


    def update      
      @gossip = Gossip.find(params[:id])
      puts "%"*10
      puts params      
      gossip_params = params.require(:gossip).permit(:title,:content)
      puts "%"*10
      if @gossip.update(title:gossip_params[:title],content:gossip_params[:content],user:@gossip.user)
        flash[:success] = "Le gossip a été mise à jour correctement."
        redirect_to @gossip
      else
        render :edit
      end
    end

    def new
      @gossip = Gossip.find(1)
      puts "$" * 60
      puts "Dans new :"
      puts params
      puts "$" * 60
    end

    def create      
      @user = User.find(11)
      puts "$" * 60
      puts "Lorsque je soumet le formulaire avec create :"
      puts params
      puts params[:title]
      puts params[:content]      
      puts "$" * 60
      @gossip = Gossip.new(title:params[:title],content:params[:content],user:@user)
      
      if @gossip.save
        flash[:success] = "Le gossip a été créé correctement."
        redirect_to gossips_path
      else
        render 'gossips/new'
      end
    end

    def destroy
      @gossip = Gossip.find(params[:id])
      @gossip.destroy
      puts "%"*50
      puts "Le gossips #{@gossip.id} a été supprimé"
      puts "%"*50

      redirect_to gossips_path
    end
end

app/controllers/profils_controller.rb
class ProfilsController < ApplicationController
  def index

  end
  def show
    @id = params[:id]
    @gossip = Gossip.find(params[:id])
    puts "%"*60    
    puts params
    puts "%"*60
  end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  def team

  end
  
  def contact

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/gossips_helper.rb
module GossipsHelper
end

app/helpers/profils_helper.rb
module ProfilsHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/views/cities/index.html.erb
<h1>Cities#index</h1>
<p>Find me in app/views/cities/index.html.erb</p>

app/views/cities/show.html.erb
<h1>City : <%= @city.name %></h1>
 <p>L'emsemble des pootins associés à la ville : </p> 

 
<div class="container text-center">
  
  <% @city.users.each do |user| %> <%# gossips est un tableau d'objet ! %>
      <p>
        <%=user.first_name  %> : <br/>
        
        <%user.gossips.each do |gossip| %>
          - id : <%= gossip.id %> - <br/>
          <%= gossip.title %><br/>
          <%= gossip.content %><br/>
        <% end %> 
      </p>
  <% end %> 
  
</div>

app/views/comments/_index.html.erb
<h4>Commentaires : </h4>

<p class="container text-center">  
  <% @gossip.comments.each do |comment| %> <%# gossips est un tableau d'objet ! %>
      <ul>      
        <li><%=comment.user.first_name  %> : <%=comment.content  %> <%= link_to "Edit", edit_gossip_comment_path(@gossip.id,comment.id), class:"btn btn-primary"%></li>           
      </ul>
  <% end %>   
</p>

app/views/comments/_new.html.erb
<h4>Ajout d'un commantaire :</h4>
<%= form_with(model: @comment, url: gossip_comments_path(@gossip)) do |form| %>
  <div class = "form-group">
    <%= form.label :content, "Comment" %>
    <%= form.text_field :content, class:"form-control" %>
  </div>  
  <div class = "form-group">    
    <button type="submit" class="btn btn-primary">Ajouter un commentaire</button>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editer un commantaire :</h1>
<%= form_with(model: @comment, url: gossip_comment_path(@gossip,@comment), method: :patch) do |form| %>
  <div class = "form-group">
    <%= form.label :content, "Comment" %>
    <%= form.text_field :content, class:"form-control" %>
  </div>  
  <div class = "form-group">    
    <button type="submit" class="btn btn-primary">Modifier le commentaire</button>
  </div>
<% end %>

<%= link_to "Destroy", gossip_comment_path(@gossip,@comment), data: {turbo: true,turbo_method: :delete,turbo_confirm: "Are you sure?"}, class:"btn btn-danger" %> <!--il faut mettre gossip_path(@gossip) pour indiquer quelle élément on veut supprimer -->
<!--Pour pouvoir utiliser turbo_confirm il faut réactiver turbo:true tout en insérarnt la bonne ligne dans application et gemfile-->

app/views/gossips/edit.html.erb
<!-- test si ya erreur affiche ce message -->
    <% if @gossip.errors.any? %>
      <div class="alert alert-danger alert-dismissible fade show" role="alert">
        <strong>Echec !</strong>
        <p>Nous n'avons pas réussi à mettre à jour le potin pour la (ou les) raison(s) suivante(s) :</p>
        <ul>
          <% @gossip.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>        
      </div>  
    <% end %>

<h1>EDIT</h1>

<%= form_with model: @gossip do |form| %>
  <div class = "form-group">
    <label>Title</label>
    <%= form.text_field :title, class:"form-control" %>
  </div>
  <div class = "form-group">
    <label>Content</label>
    <%= form.text_area :content, class:"form-control" %>
  </div>
  <div class = "form-group">
    
    <button type="submit" class="btn btn-primary">Modifier le potin</button>
  </div>
<% end %>

app/views/gossips/index.html.erb
<!-- test si ya pas d'erreur affiche ce message -->
<% if flash[:success] %>
  <div class="success">
    <div class="alert alert-success %> alert-dismissible fade show" role="alert">
      <%= flash[:success] %>
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
  </div>
<% end %>

<div class="jumbotron">
  <div class="container">
    <h1 class="display-3">Welcome <%= @first_name %></h1>
    <p>Blablabla...</p>
    <p><%= link_to "Creer un gossip", new_gossip_path, class:"btn btn-primary btn-lg"%></p>
  </div>
</div>

<div class="container text-center">
  
  <% Gossip.all.each do |gossip| %> <%# gossips est un tableau d'objet ! %>
    <div class="row">
      <div class="col-sm-3">
        <a href="<%=profil_path(gossip.id)%>" class="list-group-item list-group-item-action list-group-item-secondary">
          <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512" class="img-circle" height="30" width="30" alt="Avatar"><path d="M304 128a80 80 0 1 0 -160 0 80 80 0 1 0 160 0zM96 128a128 128 0 1 1 256 0A128 128 0 1 1 96 128zM49.3 464H398.7c-8.9-63.3-63.3-112-129-112H178.3c-65.7 0-120.1 48.7-129 112zM0 482.3C0 383.8 79.8 304 178.3 304h91.4C368.2 304 448 383.8 448 482.3c0 16.4-13.3 29.7-29.7 29.7H29.7C13.3 512 0 498.7 0 482.3z"/></svg>
            <%= gossip.user.first_name %><br/>
            <!--<%= link_to "profil", "/profil/#{gossip.id}"%> #ne peux pas etre utilisé dans une balise <a>-->
        </a>
      </div>
      <div class="col-sm-9">
        <a href="<%=gossip_path(gossip.id)%>" class="list-group-item list-group-item-action list-group-item-secondary">
          <%# on utilise l'id de l'objet gossip pour diriger vers la nouvelle page, cependant cela n'est pas suffisant, on fera que gossip.1, on doit utiliser as: 'gossip' on definit la lien /gossip/:id comme gossip, quon réutilise dans gossip_path.%>   
          <%# on pourrait aussi utiliser link_to "potin", "/gossip/#{gossip.id}", l'importance est d'utiliser l'id de gossip pour rédiriger à la bonne page%>
          <p><%= gossip.title %><br/></p>
          <p><%= gossip.comments.count %> comments</p>                    
        </a>
      </div>
    </div>    
  <% end %> 
  
</div>

app/views/gossips/new.html.erb
<html>
  <body>
    <!-- test si ya erreur affiche ce message -->
    <% if @gossip.errors.any? %>
      <div class="alert alert-danger alert-dismissible fade show" role="alert">
        <strong>Echec !</strong>
        <p>Nous n'avons pas réussi à créer le potin pour la (ou les) raison(s) suivante(s) :</p>
        <ul>
          <% @gossip.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>        
      </div>  
    <% end %>

    <!-- ... -->
    <h1>Créer un potin</h1>
    <%= form_tag gossips_path, method: "create" do %>

      <%= label_tag 'Title :' %>
      <input name="authenticity_token" type="hidden" value="<%= form_authenticity_token %>">
      <%= text_field_tag 'title', "test"  %>
      <br /> <br />

      <%= label_tag 'content :' %>
      <%= text_area_tag 'content', "teeeeeeeeest" %>
      <br /> <br />   
      
      <%= submit_tag "Submit" %>

    <% end %>

    <!-- ... -->
    

  </body>
</html>

app/views/gossips/show.html.erb
<!-- test si ya pas d'erreur affiche ce message -->
<% if flash[:success] %>
  <div class="success">
    <div class="alert alert-success %> alert-dismissible fade show" role="alert">
      <%= flash[:success] %>
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
  </div>
<% end %>

<!-- Show de 1 gossip -->
<div class="container marketing">
  <h1>Gossip#show</h1>
  <div class="row featurette">
    <div class="col-md-7">
      <h2 class="featurette-heading"><%= @gossip.content %><span >It’ll blow your mind.</span></h2>
      <h5 class="text-muted">Title : <%= @gossip.title %></h5>
      <p class="lead">Author : <%= @gossip.user.first_name %> --><%= link_to "Son profil", profil_path(@id)%></p>
      <p class="lead">City : <%= @gossip.user.city.name %> --><%= link_to "Details", city_path(@id)%></p>
      <p>
        <%= link_to "Edit", edit_gossip_path(@id), class:"btn btn-primary p-5"%>    
        <%= link_to "Destroy", gossip_path(@gossip), data: {turbo: true,turbo_method: :delete,turbo_confirm: "Are you sure?"}, class:"btn btn-danger" %> <!--il faut mettre gossip_path(@gossip) pour indiquer quelle élément on veut supprimer -->
          <!--Pour pouvoir utiliser turbo_confirm il faut réactiver turbo:true tout en insérarnt la bonne ligne dans application et gemfile-->
      </p>
    </div>
    <div class="col-md-5">
      <svg class="bd-placeholder-img bd-placeholder-img-lg featurette-image img-fluid mx-auto" width="250" height="250" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid slice" focusable="false" role="img" aria-label="Placeholder: 500x500"><title>Placeholder</title><rect width="100%" height="100%" fill="#eee"></rect><text x="50%" y="50%" fill="#aaa" dy=".3em">500x500</text></svg>
    </div>
  </div>
</div>

<!--
<p>Lien tempo pour voir les commentaire : <%= link_to "Commentaires", gossip_comments_path(@gossip.id)%></p>
-->
<br/>
<!-- compter le nombre de commentaire -->
<h5><%= @gossip.comments.count %> comments</h5>

<!-- Créer un commentaire -->
<%= render 'comments/new' %>
<!-- Affichage des commentaires -->
<%= render 'comments/index' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TheGossipProject</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", type: "module" %>

    <%# ajout de bootstrap %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.2.1/dist/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
  </head>

  <body data-turbo="false">
    <!-- utiliser pour faire apparaitre le pop up de confirmation, ne pas oublier d'inserer gem "turbo-rails", "~> 1.0" -->
    <%= javascript_include_tag "turbo", type: "module" %>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.6/dist/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.2.1/dist/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>
  

    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <a class="navbar-brand" href="/welcome">The gossip project</a>
      <%# link_to "The gossip project", welcome_path, class: "navbar-brand" %>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item">
            <%= link_to "Contact", contact_path, class: "nav-link" %>
            <%#<a class="nav-link" href="/contact">Contact</a> %>
          </li>
          <li class="nav-item">
            <%= link_to "Team", team_path, class: "nav-link" %>
            <%# <a class="nav-link" href="/team">Team</a> %>
          </li>
        </ul>
      </div>
    </nav>

    <%= yield %>
  </body>
</html>

app/views/profils/index.html.erb
<h1>Profils#index</h1>
<p>Find me in app/views/profils/index.html.erb</p>

app/views/profils/show.html.erb
<div class="container marketing">
  <h1>Profil#show</h1>
  <div class="row featurette">
    <div class="col-md-7 order-md-2">
      <h3 class="fs-2 text-body-emphasis"><%= @gossip.user.first_name %> <%= @gossip.user.last_name %></h3>
      <ul class="lead">
        <li>description : <%= @gossip.user.description %></li>
        <li>email : <%= @gossip.user.email %></li>
        <li>age : <%= @gossip.user.age %></li>
        <li>city : <%= @gossip.user.city.name %><br/><%= link_to "> En savoir plus sur la ville", city_path(@id), class:"icon-link"%> </li>    
      </ul> 
    </div>
    <div class="col-md-5 order-md-1">
      <svg class="bd-placeholder-img bd-placeholder-img-lg featurette-image img-fluid mx-auto" width="500" height="500" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid slice" focusable="false" role="img" aria-label="Placeholder: 500x500"><title>Placeholder</title><rect width="100%" height="100%" fill="#eee"></rect><text x="50%" y="50%" fill="#aaa" dy=".3em">500x500</text></svg>
    </div>
  </div>
</div>